# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CircleciAT2 < Formula
  desc "CircleCI command line tool."
  homepage "https://circleci.com"
  version "1.0.39441-pre"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.39441-pre/circleci-cli_1.0.39441-pre_darwin_amd64.tar.gz"
      sha256 "e08d5f6290d5f40a62298d958b9e5fd9f38cafdbcd64aa62166b22aae82cd4cd"

      define_method(:install) do
        bin.install "circleci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.39441-pre/circleci-cli_1.0.39441-pre_darwin_arm64.tar.gz"
      sha256 "3abb9be9b58e6259ce56cae0148a384294fc0522af455001aabc65112255e5d5"

      define_method(:install) do
        bin.install "circleci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.39441-pre/circleci-cli_1.0.39441-pre_linux_amd64.tar.gz"
      sha256 "f1a5c6e5a86c94e5f68f143fba66a1550c9f9e41ab77bf338c7743b34b65b24e"
      define_method(:install) do
        bin.install "circleci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v1.0.39441-pre/circleci-cli_1.0.39441-pre_linux_arm64.tar.gz"
      sha256 "354eafbb8bc121c99d13ecbdd6d299803034acddcda18c140511e503d894770b"
      define_method(:install) do
        bin.install "circleci"
      end
    end
  end

  keg_only :versioned_formula

  test do
    system "#{bin}/circleci", "--help"
  end
end
