# This file was generated by GoReleaser. DO NOT EDIT.
cask "chunk@next" do
  version "0.7.201"

  on_macos do
    on_arm do
      sha256 "bbbdb7600edefcbb434c452295905936a89388e1baa9682cae8fd4d49cd12eb4"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b7b0b80f691c3faa0fa7eb47d10b98ad944eca991790d5b9f69093546ee7e2d"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0c2995ec3feaa18ad55e71621277cfc28f96515075d17ea1bafe28b76cbf00dd"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "675c2ad1fd90c6a1946065f10ad8f8cc3ee720b29d9910a934b14bf5e4cfd1ae"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Linux_x86_64.tar.gz"
    end
  end

  name "chunk@next"
  desc "Chunk CLI by CircleCI (preview build)."
  homepage "https://circleci.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chunk"
  manpage "share/man/man1/chunk.1"
  bash_completion "share/bash-completion/completions/chunk"
  fish_completion "share/fish/vendor_completions.d/chunk.fish"
  zsh_completion "share/zsh/site-functions/_chunk"

  # No zap stanza required

  caveats <<~EOS
    This preview build installs a `chunk` binary that conflicts with the
    stable `chunk` formula. If you have the formula installed, unlink it
    first to avoid a clashing symlink:

      brew unlink chunk
  EOS
end
