# This file was generated by GoReleaser. DO NOT EDIT.
cask "chunk@next" do
  version "0.7.200"

  on_macos do
    on_arm do
      sha256 "78e6814e35bc0bdffb07b4564a518733f9b89aee73f58141b6ce77683798641f"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3878039c1acbf114559d4e0b96774d1872417cd531afb9f1731e78546e021b53"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f8d8c8e99976d42f0c267b8dc7527aca372e46ba3eeda45514fa515c6ea693e6"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5c99829b88f50644eb20d1286311aeb21d8df100254b8013bae5c89b2be291fe"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Linux_x86_64.tar.gz"
    end
  end

  name "chunk@next"
  desc "Chunk CLI by CircleCI (preview build)."
  homepage "https://circleci.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chunk"
  manpage "share/man/man1/chunk.1"
  bash_completion "share/bash-completion/completions/chunk"
  fish_completion "share/fish/vendor_completions.d/chunk.fish"
  zsh_completion "share/zsh/site-functions/_chunk"

  # No zap stanza required

  caveats <<~EOS
    This preview build installs a `chunk` binary that conflicts with the
    stable `chunk` formula. If you have the formula installed, unlink it
    first to avoid a clashing symlink:

      brew unlink chunk
  EOS
end
