# This file was generated by GoReleaser. DO NOT EDIT.
cask "chunk@next" do
  version "0.7.205"

  on_macos do
    on_arm do
      sha256 "142ccce3850476536dce5aa848572184bfdf4d92a3a1c204416ead56d1a195cf"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "26eef27d705baa1b05f4fc732cda920c5eb15bd8d470799d78a692c2e59fd52e"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4abee5a593f7be94d0d75de2e45a9f3ebc6d5a6d06941ca6e12d1141ecd97949"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dc113658bc2299a386f9f4ab360831983fa6f5f43119d67e19f1b366d9aa8f21"
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v#{version}/chunk-cli_Linux_x86_64.tar.gz"
    end
  end

  name "chunk@next"
  desc "Chunk CLI by CircleCI (preview build)."
  homepage "https://circleci.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chunk"
  manpage "share/man/man1/chunk.1"
  bash_completion "share/bash-completion/completions/chunk"
  fish_completion "share/fish/vendor_completions.d/chunk.fish"
  zsh_completion "share/zsh/site-functions/_chunk"

  # No zap stanza required

  caveats <<~EOS
    This preview build installs a `chunk` binary that conflicts with the
    stable `chunk` formula. If you have the formula installed, unlink it
    first to avoid a clashing symlink:

      brew unlink chunk
  EOS
end
