# This file was generated by GoReleaser. DO NOT EDIT.
cask "circleci@v0" do
  version "0.1.47860"

  on_macos do
    on_intel do
      sha256 "52990ee2c742ce0a17bb2df9ca77dd34dfd33a44cdb33f61b46e224fcec2434e"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "56c74d2494fed85692ff019138d48b93dea775ad25035b3f344ddf6f94eadc61"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "37000f009dcbe607c1d4a1af534b339aed928078225095bce7e487fb2ab32a6d"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf69596e50ff3aa9662ebaf38de6156c16d2b81383ed943d59329ffd01a122a8"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "circleci@v0"
  desc "CircleCI command line tool (legacy v0)."
  homepage "https://circleci.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "circleci-v0"
  bash_completion "share/bash-completion/completions/circleci-v0"
  zsh_completion "share/zsh/site-functions/_circleci-v0"

  # No zap stanza required

  caveats <<~EOS
    This installs the legacy v0 CLI as `circleci-v0`, so it runs alongside the
    current `circleci` (the homebrew-core formula or the `circleci@next`
    cask). Invoke the legacy CLI as `circleci-v0`.
  EOS
end
