# This file was generated by GoReleaser. DO NOT EDIT.
cask "circleci@next" do
  version "1.0.44247-pre"

  on_macos do
    on_intel do
      sha256 "56c74e3768caedf0258d2e99754f726ef7b1491ec5579c41091eede9b22635ad"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4388051ad9a4a2baa093622bf39cbb02f964277761570941a3c46c96c82241df"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "288517d94968273fd7e4c4e9789b6cb7b8b908a1df25cc77614b834f5bae2592"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfd181010e587ad1f757ead4dab699ae8c56cbdc4cb7d485238e27def6c25f1c"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "circleci@next"
  desc "CircleCI command line tool."
  homepage "https://circleci.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "circleci"
  manpage "share/man/man1/circleci.1"
  bash_completion "share/bash-completion/completions/circleci"
  fish_completion "share/fish/vendor_completions.d/circleci.fish"
  zsh_completion "share/zsh/site-functions/_circleci"

  # No zap stanza required

  caveats <<~EOS
    This preview build installs a `circleci` binary that conflicts with the
    stable `circleci` formula from homebrew-core. Homebrew cannot declare a
    cask/formula conflict automatically, so if you have the core formula
    installed, unlink it first to avoid a clashing symlink:

      brew unlink circleci
  EOS
end
