# This file was generated by GoReleaser. DO NOT EDIT.
cask "circleci@v0" do
  version "0.1.47632"

  on_macos do
    on_intel do
      sha256 "49634852d5f765ad3185b4996ccd2f076a60658a86b73c1c2eb12a6e76030865"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e590c49f1f43d0ddbfae125b5c17871633e60caa45533449d592b0b13e32a54f"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fd8768e74c3f1c163354829ce5575f4743b243257ff75ff4c6acbf6f781f5b02"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8979e9617c9c74c7116162c822ef1531d441321bd3cb3d096ee784fed0da3df"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "circleci@v0"
  desc "CircleCI command line tool (legacy v0)."
  homepage "https://circleci.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "circleci"
  bash_completion "share/bash-completion/completions/circleci"
  zsh_completion "share/zsh/site-functions/_circleci"

  # No zap stanza required

  caveats <<~EOS
    This installs the legacy v0 `circleci` binary, which conflicts with the
    stable `circleci` formula from homebrew-core and the `circleci@next`
    preview cask. Homebrew cannot declare a cask/formula conflict
    automatically, so if you have either installed, unlink it first to avoid a
    clashing symlink:

      brew unlink circleci
  EOS
end
