# This file was generated by GoReleaser. DO NOT EDIT.
cask "circleci@next" do
  version "1.0.48386"

  on_macos do
    on_intel do
      sha256 "6e7088ce496428355394bdd6ca814806f9e5e4597b335bc511c61d72acef7407"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "46538520d0e1f01c80b4cb675dad07ea22347817f1c3726bde872bf7de5cce2b"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ea6bc5cf768b84d67b79e26d182634f7f9284931797afe4e85b52f8f6adf35b"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce1e768af93b77ccd6f28ee3e68c453c4dbc73b894d0988ce4f39b7b6ab75d51"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "circleci@next"
  desc "CircleCI command line tool."
  homepage "https://circleci.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "circleci"
  manpage "share/man/man1/circleci.1"
  bash_completion "share/bash-completion/completions/circleci"
  fish_completion "share/fish/vendor_completions.d/circleci.fish"
  zsh_completion "share/zsh/site-functions/_circleci"

  # No zap stanza required

  caveats <<~EOS
    This preview build installs a `circleci` binary that conflicts with the
    stable `circleci` formula from homebrew-core. Homebrew cannot declare a
    cask/formula conflict automatically, so if you have the core formula
    installed, unlink it first to avoid a clashing symlink:

      brew unlink circleci
  EOS
end
