# This file was generated by GoReleaser. DO NOT EDIT.
cask "circleci@next" do
  version "1.0.42029-pre"

  on_macos do
    on_intel do
      sha256 "bcbeede04679f738501458c192180b204a91189fcf07e4c34304d52e4b69d053"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "37b488a0e859dee07d02e96f65ab11564037b3cae96df98a0fd4f89336097988"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2caf66de3b27e0e3c00a244bad2cb6da71db4a883d92e2b0623408524ed23567"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "439d9caf6260c2fdd13479146846f381fd907f2d117f69da5bd4da0ce2a6ff38"
      url "https://github.com/CircleCI-Public/circleci-cli/releases/download/v#{version}/circleci-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "circleci@next"
  desc "CircleCI command line tool."
  homepage "https://circleci.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "circleci"
  manpage "share/man/man1/circleci.1"
  bash_completion "share/bash-completion/completions/circleci"
  zsh_completion "share/zsh/site-functions/_circleci"

  # No zap stanza required

  caveats <<~EOS
    This preview build installs a `circleci` binary that conflicts with the
    stable `circleci` formula from homebrew-core. Homebrew cannot declare a
    cask/formula conflict automatically, so if you have the core formula
    installed, unlink it first to avoid a clashing symlink:

      brew unlink circleci
  EOS
end
