version: 2.1

parameters:
  run_smoketest:
    default: false
    type: boolean

workflows:
  version: 2
  build:
    when:
      not: << pipeline.parameters.run_smoketest >>
    jobs:
      - install_and_run:
          context: 
            - runner-brew-test

  smoketest:
    when: << pipeline.parameters.run_smoketest >>
    jobs:
      - smoketest


jobs:
  install_and_run:
    macos:
      xcode: 14.3.1
    steps:
      - run: echo "this is a place holder to get the smoketest job setup"  

  smoketest:
    machine: true
    resource_class: circleci/brew-test-runner
    steps:
      - run: echo "Hello world, I'm running on a runner installed from a brew package"
