version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.1.0
  continuation: circleci/continuation@1.0.0

parameters:
  run_smoketest:
    default: false
    type: boolean

workflows:
  setup:
    when:
      not: << pipeline.parameters.run_smoketest >>
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/runner_brew_test.yml
          mapping: |
            Casks/circleci-runner\.rb run_tests true

  smoketest-continue:
    when: << pipeline.parameters.run_smoketest >>
    jobs:
      - continue-smoketest

jobs:
  continue-smoketest:
    executor: continuation/default
    steps:
      - continuation/continue:
          configuration_path: .circleci/runner_brew_test.yml
          parameters: '{"run_smoketest": true}'
