# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chunk < Formula
  desc "Chunk CLI by CircleCI"
  homepage "https://github.com/CircleCI-Public/chunk-cli"
  version "0.7.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.7.14/chunk-cli_Darwin_x86_64.tar.gz"
      sha256 "0f0d99fe696ee77fd6bb430f2e55d5f7218db7e929626930b16236216a0ff60e"

      define_method(:install) do
        bin.install "chunk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.7.14/chunk-cli_Darwin_arm64.tar.gz"
      sha256 "2a332557e9681d3fcd3e70cc12f55312f222ff128d20dfcd855fbefc9cbc3319"

      define_method(:install) do
        bin.install "chunk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.7.14/chunk-cli_Linux_x86_64.tar.gz"
      sha256 "2287d95b1267e4805d6bc593ea60c18aee8aff409c0f488a560e8e3f245053e5"
      define_method(:install) do
        bin.install "chunk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CircleCI-Public/chunk-cli/releases/download/v0.7.14/chunk-cli_Linux_arm64.tar.gz"
      sha256 "6f04570b8e221ffc6190dffa7e7941ef26ccf03e75c4e38781abc96663c317ef"
      define_method(:install) do
        bin.install "chunk"
      end
    end
  end

  test do
    system "#{bin}/chunk"
  end
end
